import React, { useEffect, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { operationalSearch, safeCommand } from "../../services/operationalControl";

const NAV = [
  { label: "Receipts", kind: "navigation", type: "Command", path: "#/receipts" },
  { label: "Approvals", kind: "navigation", type: "Command", path: "#/approvals" },
  { label: "Audit log", kind: "navigation", type: "Command", path: "#/audit" },
];

export function OperationalPalette({ client, onNavigate = (path) => { window.location.hash = path.slice(1); } }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [results, setResults] = useState([]);
  const [active, setActive] = useState(0); const [state, setState] = useState("idle"); const trigger = useRef(null); const input = useRef(null);
  useEffect(() => { const key = (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen(true); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  useEffect(() => { if (open) input.current?.focus(); else trigger.current?.focus(); }, [open]);
  useEffect(() => { if (!open) return; const controller = new AbortController(); const timer = setTimeout(async () => { setState("loading"); try { const remote = await operationalSearch(client, query); if (!controller.signal.aborted) { setResults([...NAV.filter((x) => x.label.toLowerCase().includes(query.toLowerCase())), ...remote.results]); setActive(0); setState("ready"); } } catch { if (!controller.signal.aborted) setState("error"); } }, 250); return () => { controller.abort(); clearTimeout(timer); }; }, [client, open, query]);
  const choose = (item) => { if (!item) return; if (safeCommand(item)) onNavigate(item.path); else if (item.path && /^#\/[^?#]+$/.test(item.path)) onNavigate(item.path); setOpen(false); };
  const onKeyDown = (event) => { if (event.key === "Escape") { event.preventDefault(); setOpen(false); } if (event.key === "ArrowDown") { event.preventDefault(); setActive((n) => Math.min(results.length - 1, n + 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((n) => Math.max(0, n - 1)); } if (event.key === "Enter") { event.preventDefault(); choose(results[active]); } };
  return <><button ref={trigger} type="button" className="operation-search-trigger" onClick={() => setOpen(true)} aria-haspopup="dialog"><Search aria-hidden="true" /> <span>Search</span><kbd>⌘/Ctrl K</kbd></button>{open && <div className="operation-dialog-backdrop" onMouseDown={(e) => e.target === e.currentTarget && setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="operation-search-title" className="operation-dialog" onKeyDown={onKeyDown}><h2 id="operation-search-title">Global command and search</h2><button type="button" onClick={() => setOpen(false)} aria-label="Close search"><X aria-hidden="true" /></button><label htmlFor="operation-search-input">Search authorized records</label><input ref={input} id="operation-search-input" role="combobox" aria-expanded="true" aria-controls="operation-search-results" aria-activedescendant={results[active] ? `operation-result-${active}` : undefined} autoComplete="off" value={query} onChange={(e) => setQuery(e.target.value)} /><p className="sr-only" aria-live="polite">{state === "loading" ? "Searching" : state === "error" ? "Search failed" : `${results.length} authorized results`}</p><ul id="operation-search-results" role="listbox">{state === "error" && <li role="alert">Search could not be completed.</li>}{state === "ready" && !results.length && <li>No authorized results.</li>}{results.map((item, index) => <li key={`${item.type}-${item.path}-${index}`} id={`operation-result-${index}`} role="option" aria-selected={active === index}><button type="button" onMouseEnter={() => setActive(index)} onClick={() => choose(item)}><strong>{item.label}</strong><span>{item.type}{item.context ? ` · ${item.context}` : ""}</span></button></li>)}</ul></section></div>}</>;
}
